apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inception-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dugonzal/dugonzal_ci_di.git
    targetRevision: HEAD
    path: manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
